---

- name: Create cobbler dirs
  file: path={{ item }} state=directory mode=0755
  with_items:
    - /var/www/nailgun/ubuntu/x86_64/images
    - /var/www/nailgun/bootstraps/bootstrap_stub

- name: Create dummy bootstrap files
  file: path={{ item }} state=touch mode=0755
  with_items:
    - /var/www/nailgun/ubuntu/x86_64/images/linux
    - /var/www/nailgun/ubuntu/x86_64/images/initrd.gz
    - /var/www/nailgun/bootstraps/bootstrap_stub/vmlinuz
    - /var/www/nailgun/bootstraps/bootstrap_stub/initrd.img

- name: Create initial symlink
  file:
    src: /var/www/nailgun/bootstraps/bootstrap_stub
    dest: /var/www/nailgun/bootstraps/active_bootstrap
    state: link
