---

- name: Setup admin network interface
  include: admin_iface.yaml

- name: Switch SELinux to permissive mode (needed by rabbitmq)
  selinux: policy=targeted state=permissive

- name: Install Yum Priorities plugin
  yum: name=yum-plugin-priorities state=present

- name: Setup RPM repo
  yum_repository:
    name: '{{ item.name }}'
    description: '{{ item.name }}'
    priority: '{{ item.priority }}'
    baseurl: '{{ item.uri }}'
    gpgcheck: 'no'
  with_items: '{{ rpm_repos }}'

- name: Install packages
  include: packages.yaml

- name: Apply cobbler workarounds
  include: cobbler_workarounds.yaml

- name: Create /etc/fuel/ for astute.yaml
  file: path=/etc/fuel state=directory mode=0755

- name: Setup astute.yaml
  template:
    src: ../templates/astute.yaml.j2
    dest: /etc/fuel/astute.yaml
    owner: root
    group: root
    mode: 0644

- name: Apply puppet task
  puppet: manifest="{{ puppet_path }}{{ item }}.pp" logdest=syslog
  with_items: "{{ puppet_tasks }}"

- name: Build bootstrap image
  command: fuel-bootstrap -v --debug build --activate
  args:
    creates: /var/www/nailgun/bootstraps/active_bootstrap/metadata.yaml
