---

- name: Install Fuel Setup
  yum: name=fuel-setup state=present

- name: Install Fuel packages
  yum: name=fuel-library10.0,fuel-utils,fuel-ui state=present

- name: Install required packages
  yum: name=puppet,sysstat,gdisk state=present