---

- name: Create admin node
  command: >-
    nova boot
    --flavor m1.medium
    --image {{ fuel_admin_node.image }}
    --nic net-name=fuel_public,v4-fixed-ip={{fuel_admin_node.fixed_ip}}
    --nic net-name=fuel_pxe,v4-fixed-ip={{fuel_admin_node.fixed_pxe_ip}}
    --security-group open
    --key-name {{ fuel_admin_node.key }}
    {{ fuel_admin_node.name }}

- name: Open admin node
  command: nova add-secgroup {{fuel_admin_node.name}} {{fuel_admin_node.secgroup}}

- name: "FIXME: Assign floating IP"
  command: >-
    nova floating-ip-associate
    {{fuel_admin_node.name}}
    {{fuel_admin_node.floating_ip}}
    --fixed-address {{fuel_admin_node.fixed_ip}}
