---

- name: "setup secgroup"
  include: security.yaml

- name: "create networks"
  include: network.yaml
  with_dict: "{{ fuel_networks }}"
  tags:
    - networks

- name: "create router"
  include: router.yaml
  tags:
    - router

- name: "create admin node"
  include: admin_node.yaml

- name: "create nodes"
  include: node.yaml
  with_sequence: start=1 end={{fuel_node.number}} format=fuel-node%02x