---

- name: "setup secgroup"
  include: security.yaml

- name: "create networks"
  include: network.yaml
  with_dict: "{{ fuel_networks }}"
  tags:
    - networks

- name: "create router"
  include: router.yaml
  tags:
    - router

- name: "create nodes"
  include: nodes.yaml
