---

- name: Create router
  command: neutron router-create {{fuel_router}}

- name: Add gateway to external network
  command: neutron router-gateway-set {{fuel_router}} {{ external_network }}

- name: Add interface to fuel public network
  command: neutron router-interface-add {{fuel_router}} {{fuel_networks.public.subnet_name}}

- name: Add Google DNS to public network
  command: >-
    neutron subnet-update {{fuel_networks.public.subnet_name}}
    --dns-nameservers list=true 8.8.8.8 8.8.4.4