---

- name: Create security group
  command: nova secgroup-create {{secgroup}} "Open security group"

- name: Allow port access for security group
  command: nova secgroup-add-rule {{secgroup}} tcp {{item}} {{item}} 0.0.0.0/0
  with_items:
    - 22
    - 8000