---

- name: Create security group
  command: nova secgroup-create {{secgroup}} "Open security group"

- name: Allow SSH access for security group
  command: nova secgroup-add-rule {{secgroup}} tcp 22 22 0.0.0.0/0

- name: Allow HTTP access for security group
  command: nova secgroup-add-rule {{secgroup}} tcp 80 80 0.0.0.0/0

- name: Allow HTTPS access for security group
  command: nova secgroup-add-rule {{secgroup}} tcp 443 443 0.0.0.0/0