---

network_settings_yaml: |
  "HOSTNAME": "fuel"
  "DNS_DOMAIN": "localdomain"
  "DNS_SEARCH": "routed-130"
  "DNS_UPSTREAM": "192.168.130.1"
  "ADMIN_NETWORK":
    "interface": "eth1"
    "ipaddress": "192.168.140.2"
    "netmask": "255.255.255.0"
    "cidr": "192.168.140.0/24"
    "size": "256"
    "dhcp_gateway": "192.168.140.2"
    "dhcp_pool_start": "192.168.140.101"
    "dhcp_pool_end": "192.168.140.254"
    "ssh_network": "192.168.0.0/16"
    "mac": "52:54:00:cc:4e:05"

puppet_tasks:
  - hiera
  - host
  - cobbler
  - postgresql
  - rabbitmq
  - mcollective
  - astute
  - keystone
  - nailgun
  - ostf
  - nginx_repo
  - nginx_services
  - client
  - rsyslog
  - puppetsync

puppet_path: "/etc/puppet/modules/fuel/examples/"