---

required_packages:
  - puppet
  - sysstat
  - gdisk

other_packages:
  - augeas
  - authconfig
  - bind-utils
  - bridge-utils
  - daemonize
  - dhcp
  - docker
  - fuel
  - fuel-bootstrap-cli
  - fuel-openstack-metadata
  - fuel-utils
  - fuel-ui
  - lrzip
  - lsof
  - mlocate
  - nmap-ncat
  - ntp
  - ntpdate
  - python-pypcap
  - python-timmy
  - rsync
  - rubygem-netaddr
  - rubygem-openstack
  - send2syslog
  - strace
  - system-config-firewall-base
  - tcpdump
  - telnet
  - vim
  - virt-what
  - wget

network_settings_yaml: |
  "HOSTNAME": "fuel"
  "DNS_DOMAIN": "localdomain"
  "DNS_SEARCH": "openstacklocal"
  "DNS_UPSTREAM": "8.8.8.8"
  "ADMIN_NETWORK":
    "interface": "eth1"
    "ipaddress": "192.168.140.2"
    "netmask": "255.255.255.0"
    "cidr": "192.168.140.0/24"
    "size": "256"
    "dhcp_gateway": "192.168.140.2"
    "dhcp_pool_start": "192.168.140.101"
    "dhcp_pool_end": "192.168.140.254"
    "ssh_network": "192.168.0.0/0"
    "mac": "52:54:00:cc:4e:05"

puppet_tasks:
  - hiera
  - host
  - cobbler
  - postgresql
  - rabbitmq
  - mcollective
  - astute
  - keystone
  - nailgun
  - ostf
  - nginx_repo
  - nginx_services
  - client
  - rsyslog
  - puppetsync

puppet_path: "/etc/puppet/modules/fuel/examples/"
